#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

PWM_PATH="/sys/devices/platform/pwm-fan/hwmon/hwmon2/pwm1"
TEMP_PATH="/sys/class/thermal/thermal_zone0/temp"

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/fancontrol.sh
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
